version: "3.8"

services:
  # Base de données PostgreSQL pour Airflow
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data
    networks:
      - airflow_network

  # Initialisation d'Airflow (DB + utilisateur admin)
  airflow-init:
    image: apache/airflow:2.7.1
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
      - hadoop_datanode:/mnt/hadoop_data
    entrypoint: bash -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --email admin@example.com --role Admin"
    networks:
      - airflow_network

  # Serveur Web Airflow
  airflow-webserver:
    build:
      context: ./ 
      dockerfile: apache.dockerfile
    restart: always
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - airflow-init
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
      - hadoop_datanode:/mnt/hadoop_data
    command: webserver
    networks:
      - airflow_network

  # Scheduler d'Airflow
  airflow-scheduler:
    build:
      context: ./ 
      dockerfile: apache.dockerfile
    restart: always
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - hadoop_datanode:/mnt/hadoop_data
      - /var/run/docker.sock:/var/run/docker.sock
    command: scheduler
    depends_on:
      - postgres
    networks:
      - airflow_network

  # Hadoop NameNode
  namenode:
    build:
      context: ./
      dockerfile: namenode.Dockerfile
    container_name: namenode
    ports:
      - "9870:9870"
    volumes:
      - namenode_data:/hadoop/dfs/name
      - hadoop_datanode:/mnt/hadoop_data
      - ./scripts:/tmp/
      - ./scripts/mapper.py:/tmp/mapper.py
      - ./scripts/reducer.py:/tmp/reducer.py
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
      - CLUSTER_NAME=test
    networks:
      - airflow_network

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    ports:
      - "9864:9864"
    volumes:
      - datanode1_data:/hadoop/dfs/data
      - hadoop_datanode:/mnt/hadoop_data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
      - CLUSTER_NAME=test
    depends_on:
      - namenode
    networks:
      - airflow_network

  # HBase 
  hbase:
    image: harisekhon/hbase
    container_name: hbase
    ports:
      - "16010:16010"
      - "9090:9090"
    environment:
      - HBASE_MANAGES_ZK=True
    depends_on:
      - namenode
      - datanode1
    networks:
      - airflow_network

volumes:
  postgres_db_volume:
  hadoop_datanode:
  namenode_data:
  datanode1_data:

networks:
  airflow_network:
    driver: bridge